# Generated by Django 5.2.7 on 2025-11-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_is_pdf_dataset_from_pdf_remove_dataset_paper_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='website',
            new_name='url',
        ),
    ]
