# Generated by Django 5.2.7 on 2025-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_remove_dataset_culo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='PDF URL'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='code_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Code URL'),
        ),
    ]
